### PR TITLE
Add `cargo-deny` checks

### LINKED ISSUE #128: Ensure permissively licensed dependencies using `cargo-deny`
We cannot include GPL or closed source code in an MIT project.

Enforce this using https://github.com/EmbarkStudios/cargo-deny

### PR DESCRIPTION
**Pull request by TimJentzsch**
Closes #128.

This PR adds configurations for `cargo-deny` to check for licensing issues.
It also adds a workflow to run `cargo-deny` in CI.

Note that compared to Bevy's `deny.toml`, added license allows for the following:
- [`BSL-1.0`](https://opensource.org/licenses/BSL-1.0). This seems to be a rather permissive license.
- [`OFL-1.1`](https://opensource.org/licenses/OFL-1.1). We use this for our own fonts, so this should be fine.
- [`LicenseRef-UFL-1.0`](https://tldrlegal.com/license/ubuntu-font-license,-1.0), but only for `epaint` (dependency of `egui`). We should double check this one.

# TODO

- [x] #140
- [x] Do we want to add the checks for security advisories, duplicate dependencies, etc. as well?
- [x] #154
- [x] <https://github.com/EmbarkStudios/cargo-deny/issues/488>

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
For the second point yes, I think we should.

**Comment by bzm3r** [comment]
@TimJentzsch I merged main into this branch of yours, so maybe you will want to update it locally too! Probably should not have done that myself, and should have let you handle it. My mistake!

**Comment by alice-i-cecile** [comment]
> Git imports are counted as wildcard dependency, even if the commit hash is fixed

We should file an issue for this upstream, and then override it here IMO.

**Comment by TimJentzsch** [comment]
> > Git imports are counted as wildcard dependency, even if the commit hash is fixed
> 
> We should file an issue for this upstream, and then override it here IMO.

Done: <https://github.com/EmbarkStudios/cargo-deny/issues/488>

**Comment by TimJentzsch** [comment]
I allowed the things that are not working for now so we can get this merged.
See #193 and #194.

**Pull request merged**
